# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AsertoIdpSeed < Formula
  desc "Aserto IDP seed tool"
  homepage "https://aserto.com/"
  version "0.0.12"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/aserto-dev/aserto-idp-seed/releases/download/v0.0.12/aserto-idp-seed_0.0.12_darwin_x86_64.zip"
    sha256 "a8ed3266f48b8ed80d266f9bfb9d7dc83c5acdb15e2cb3f7944959c44c7d076f"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/aserto-dev/aserto-idp-seed/releases/download/v0.0.12/aserto-idp-seed_0.0.12_linux_x86_64.zip"
    sha256 "303f2f50b1b59b1e1def2e556ff212acaf989865a2a7eb7391191b4a4ab315e6"
  end

  def install
    bin.install "aserto-idp-seed"
  end

  test do
    system "#{bin}/aserto-idp-seed version"
  end
end
