# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aserto < Formula
  desc "Aserto CLI"
  homepage "https://docs.aserto.com/"
  version "0.8.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://storage.googleapis.com/aserto-cli/aserto/0.8.13/aserto_darwin_arm64.zip", :using => CurlDownloadStrategy
      sha256 "bbfa5a941183811df961f6a0f9a2e6661cbafd3a7db1d3915be3d207a5dbf178"

      def install
        bin.install "aserto"
      end
    end
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/aserto-cli/aserto/0.8.13/aserto_darwin_x86_64.zip", :using => CurlDownloadStrategy
      sha256 "1ed2477117c61cafec5f2b2de6b1ac499728f0c2e73dcad87f710fcfcf5b1aad"

      def install
        bin.install "aserto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://storage.googleapis.com/aserto-cli/aserto/0.8.13/aserto_linux_arm64.zip", :using => CurlDownloadStrategy
      sha256 "6ccbd415be4d11a495d80c221698b4142915d642bd0e6a59790bb6561d2ae84f"

      def install
        bin.install "aserto"
      end
    end
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/aserto-cli/aserto/0.8.13/aserto_linux_x86_64.zip", :using => CurlDownloadStrategy
      sha256 "02ad49c31322a0f5849ac658f00b09fa7a755d04028fdc89212d8651de9083f2"

      def install
        bin.install "aserto"
      end
    end
  end

  test do
    system "#{bin}/aserto version"
  end
end
