# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AsertoTest < Formula
  desc "Aserto Test Runner"
  homepage "https://docs.aserto.com/"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://storage.googleapis.com/aserto-cli/aserto-test/0.0.3/aserto-test_darwin_arm64.zip", :using => CurlDownloadStrategy
      sha256 "3fa68b29060f084f5eba65913e045a69469fe851b43a544dd91daf6272f23fbf"

      def install
        bin.install "aserto-test"
      end
    end
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/aserto-cli/aserto-test/0.0.3/aserto-test_darwin_x86_64.zip", :using => CurlDownloadStrategy
      sha256 "3e6e95304be79066ffd300d393c56ce00df1e08504dc8139ba4b1cf4867fdff9"

      def install
        bin.install "aserto-test"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://storage.googleapis.com/aserto-cli/aserto-test/0.0.3/aserto-test_linux_arm64.zip", :using => CurlDownloadStrategy
      sha256 "ec674751f468fb32a73991803637049645abf1a2679592826bebc833b43d7c67"

      def install
        bin.install "aserto-test"
      end
    end
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/aserto-cli/aserto-test/0.0.3/aserto-test_linux_x86_64.zip", :using => CurlDownloadStrategy
      sha256 "df7074b65f148d00ebccfdce39ba909d8d77c17e3653a9896778f789c7acbaf1"

      def install
        bin.install "aserto-test"
      end
    end
  end

  test do
    system "#{bin}/aserto-test version"
  end
end
