# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AsertoIdp < Formula
  desc "Aserto IDP CLI"
  homepage "https://aserto.com/"
  version "0.8.4"
  license "Apache License Version 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aserto-dev/aserto-idp/releases/download/v0.8.4/aserto-idp0.8.4_darwin_arm64.zip"
      sha256 "08779e92011e70d3e4e718275b07ab2d7459dafd2c590eb58a00790457420dca"

      def install
        bin.install "aserto-idp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aserto-dev/aserto-idp/releases/download/v0.8.4/aserto-idp0.8.4_darwin_x86_64.zip"
      sha256 "ffb4ab1a4245f28f9601f5833a3b962b6720e16b4e4d64155e902f8eaab901fe"

      def install
        bin.install "aserto-idp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aserto-dev/aserto-idp/releases/download/v0.8.4/aserto-idp0.8.4_linux_arm64.zip"
      sha256 "b389ae72eba764daee550253119d5d005c2b93bfa19b490f371f91b97b367916"

      def install
        bin.install "aserto-idp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aserto-dev/aserto-idp/releases/download/v0.8.4/aserto-idp0.8.4_linux_x86_64.zip"
      sha256 "3d4818977e3def819a3f176f086a00da0e7cbfc53dfa09ecbce18facadab037a"

      def install
        bin.install "aserto-idp"
      end
    end
  end

  test do
    system "#{bin}/aserto-idp version"
  end
end
