# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aserto < Formula
  desc "Aserto CLI"
  homepage "https://docs.aserto.com/"
  version "0.32.8"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/aserto-dev/aserto/releases/download/v0.32.8/aserto_darwin_x86_64.zip", using: CurlDownloadStrategy
      sha256 "eb85929b81dedc43ca4c51273df082e15672253c415e2cfafd7b163aa0e61265"

      def install
        bin.install "aserto"
      end
    end
    on_arm do
      url "https://github.com/aserto-dev/aserto/releases/download/v0.32.8/aserto_darwin_arm64.zip", using: CurlDownloadStrategy
      sha256 "94301f9d8e19a896d47467903f94cd580376f920af5c45c57a28126cf8697f98"

      def install
        bin.install "aserto"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aserto-dev/aserto/releases/download/v0.32.8/aserto_linux_x86_64.zip", using: CurlDownloadStrategy
        sha256 "5b1366e02c41e66164334d8ae20e22cf5b6ff5f90e378df7c81e8ac002832063"

        def install
          bin.install "aserto"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aserto-dev/aserto/releases/download/v0.32.8/aserto_linux_arm64.zip", using: CurlDownloadStrategy
        sha256 "dab2f88ce2b5a60b71590803d3609bfc70933e0d45764c1762ce14f766763025"

        def install
          bin.install "aserto"
        end
      end
    end
  end

  test do
    system "#{bin}/aserto version"
  end
end
