# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Check2decision < Formula
  desc "Converts directory check assertions into authorizer check_decision assertions"
  homepage "https://github.com/aserto-dev/check2decision"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aserto-dev/check2decision/releases/download/v0.0.3/check2decision_darwin_arm64.zip", using: CurlDownloadStrategy
      sha256 "2459a58627d6c8ced89845f8c70b1ff35855bbcff77255de0e19032da3aaaf57"

      def install
        bin.install "check2decision"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aserto-dev/check2decision/releases/download/v0.0.3/check2decision_darwin_x86_64.zip", using: CurlDownloadStrategy
      sha256 "dd15bb2b0db245fd8835644e5aa2d9111238918737c004542d680d6527716e1f"

      def install
        bin.install "check2decision"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aserto-dev/check2decision/releases/download/v0.0.3/check2decision_linux_arm64.zip", using: CurlDownloadStrategy
      sha256 "728950f410273625c311792febfde94c7301c69b21557688e968bb714f653297"

      def install
        bin.install "check2decision"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aserto-dev/check2decision/releases/download/v0.0.3/check2decision_linux_x86_64.zip", using: CurlDownloadStrategy
      sha256 "1c804ea58375b7dbbadc328b0f0c396d62f93ada7487e9fcc35a002b49fa929e"

      def install
        bin.install "check2decision"
      end
    end
  end

  test do
    system "#{bin}/check2decision --version"
  end
end
