# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Check2decision < Formula
  desc "Converts directory check assertions into authorizer check_decision assertions"
  homepage "https://github.com/aserto-dev/check2decision"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aserto-dev/check2decision/releases/download/v0.0.4/check2decision_darwin_x86_64.zip", using: CurlDownloadStrategy
      sha256 "51a8ce45e44884034a58c6dfd168e5c6e2ee223b8ddb64fc151c5ee40e303772"

      def install
        bin.install "check2decision"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aserto-dev/check2decision/releases/download/v0.0.4/check2decision_darwin_arm64.zip", using: CurlDownloadStrategy
      sha256 "5f1e630260ff19c8f9b749d4fdb4424125d3ef33e36c6352a71ca0d07674be5f"

      def install
        bin.install "check2decision"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aserto-dev/check2decision/releases/download/v0.0.4/check2decision_linux_arm64.zip", using: CurlDownloadStrategy
      sha256 "6d3df5963613a9e5804b4f028cd2d5e8cacf35b3642779ce06f9cc424857bcea"

      def install
        bin.install "check2decision"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aserto-dev/check2decision/releases/download/v0.0.4/check2decision_linux_x86_64.zip", using: CurlDownloadStrategy
      sha256 "3d6dcf10cbe789797c486653b4186fec5ea13ec3258f86600720cb3c7473920b"

      def install
        bin.install "check2decision"
      end
    end
  end

  test do
    system "#{bin}/check2decision --version"
  end
end
