# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Check2decision < Formula
  desc "Converts directory check assertions into authorizer check_decision assertions"
  homepage "https://github.com/aserto-dev/check2decision"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aserto-dev/check2decision/releases/download/v0.0.5/check2decision_darwin_arm64.zip", using: CurlDownloadStrategy
      sha256 "1b1000ca38ecc854ba2c60fdc22db52f732cfc364a86741d871c96790a0b581b"

      def install
        bin.install "check2decision"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aserto-dev/check2decision/releases/download/v0.0.5/check2decision_darwin_x86_64.zip", using: CurlDownloadStrategy
      sha256 "13e4b0fbcd74f337c5de22493073ff8c8d8e05150ce59a8b944cb31d5cb741fe"

      def install
        bin.install "check2decision"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aserto-dev/check2decision/releases/download/v0.0.5/check2decision_linux_x86_64.zip", using: CurlDownloadStrategy
      sha256 "c76067ac5e8b3bcfc299394c770efa8d53e76938fe95c3c3285c054e2e529422"

      def install
        bin.install "check2decision"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aserto-dev/check2decision/releases/download/v0.0.5/check2decision_linux_arm64.zip", using: CurlDownloadStrategy
      sha256 "1c007e547d596cdd47c22aacf0bdc0f5281e0c50a28b4f0d40bbaf869e6846d2"

      def install
        bin.install "check2decision"
      end
    end
  end

  test do
    system "#{bin}/check2decision --version"
  end
end
