# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DsLoad < Formula
  desc "DS Load CLI"
  homepage "https://docs.aserto.com/"
  version "0.31.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/aserto-dev/ds-load/releases/download/v0.31.0/ds-load_0.31.0_darwin_x86_64.zip", using: CurlDownloadStrategy
      sha256 "696c7befcb7549acf5ac7383c54543920361a4759e028ee0de25a21b93790d82"

      def install
        bin.install "ds-load"
        bin.install "ds-load-auth0"
        bin.install "ds-load-azuread"
        bin.install "ds-load-azureadb2c"
        bin.install "ds-load-cognito"
        bin.install "ds-load-fusionauth"
        bin.install "ds-load-google"
        bin.install "ds-load-ldap"
        bin.install "ds-load-okta"
        bin.install "ds-load-openapi"
      end
    end
    on_arm do
      url "https://github.com/aserto-dev/ds-load/releases/download/v0.31.0/ds-load_0.31.0_darwin_arm64.zip", using: CurlDownloadStrategy
      sha256 "e6616ed3140af4bdc224010753dc664dd03190a62f0216c9fe55318cf3035726"

      def install
        bin.install "ds-load"
        bin.install "ds-load-auth0"
        bin.install "ds-load-azuread"
        bin.install "ds-load-azureadb2c"
        bin.install "ds-load-cognito"
        bin.install "ds-load-fusionauth"
        bin.install "ds-load-google"
        bin.install "ds-load-ldap"
        bin.install "ds-load-okta"
        bin.install "ds-load-openapi"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aserto-dev/ds-load/releases/download/v0.31.0/ds-load_0.31.0_linux_x86_64.zip", using: CurlDownloadStrategy
        sha256 "951d7376c102e5c03d3eb15a1d3b9a32e38c50c3c55ceab18690870bba82f6aa"

        def install
          bin.install "ds-load"
          bin.install "ds-load-auth0"
          bin.install "ds-load-azuread"
          bin.install "ds-load-azureadb2c"
          bin.install "ds-load-cognito"
          bin.install "ds-load-fusionauth"
          bin.install "ds-load-google"
          bin.install "ds-load-ldap"
          bin.install "ds-load-okta"
          bin.install "ds-load-openapi"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aserto-dev/ds-load/releases/download/v0.31.0/ds-load_0.31.0_linux_arm64.zip", using: CurlDownloadStrategy
        sha256 "2a8960735350baebab410b59ea277633e146a8b5cd0557a33a40c5c1f83e9ec0"

        def install
          bin.install "ds-load"
          bin.install "ds-load-auth0"
          bin.install "ds-load-azuread"
          bin.install "ds-load-azureadb2c"
          bin.install "ds-load-cognito"
          bin.install "ds-load-fusionauth"
          bin.install "ds-load-google"
          bin.install "ds-load-ldap"
          bin.install "ds-load-okta"
          bin.install "ds-load-openapi"
        end
      end
    end
  end

  test do
    system "#{bin}/ds-load version"
  end
end
