# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DsLoad < Formula
  desc "DS Load CLI"
  homepage "https://docs.aserto.com/"
  version "0.0.21"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aserto-dev/ds-load/releases/download/v0.0.21/ds-load_0.0.21_darwin_x86_64.zip", using: CurlDownloadStrategy
      sha256 "874ff10bd6558ba2c8598c19d7554f4c642b091cd90fe5bf44fb468f5eedde92"

      def install
        bin.install "ds-load"
        bin.install "ds-load-auth0"
        bin.install "ds-load-azuread"
        bin.install "ds-load-okta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aserto-dev/ds-load/releases/download/v0.0.21/ds-load_0.0.21_darwin_arm64.zip", using: CurlDownloadStrategy
      sha256 "70b2ae4d60c19d424ccdbedce0dfe1676219484f5147d9010bd1d23b53b03fac"

      def install
        bin.install "ds-load"
        bin.install "ds-load-auth0"
        bin.install "ds-load-azuread"
        bin.install "ds-load-okta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aserto-dev/ds-load/releases/download/v0.0.21/ds-load_0.0.21_linux_x86_64.zip", using: CurlDownloadStrategy
      sha256 "8ec4249c066e3b682cb94ee841df8fb314fe902c4b23c5c66b5b8c385740ab89"

      def install
        bin.install "ds-load"
        bin.install "ds-load-auth0"
        bin.install "ds-load-azuread"
        bin.install "ds-load-okta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aserto-dev/ds-load/releases/download/v0.0.21/ds-load_0.0.21_linux_arm64.zip", using: CurlDownloadStrategy
      sha256 "381499c53b39f5f11f6449cce7c4161ac5a013a413b047a7e02fa52a43ceb2fe"

      def install
        bin.install "ds-load"
        bin.install "ds-load-auth0"
        bin.install "ds-load-azuread"
        bin.install "ds-load-okta"
      end
    end
  end

  test do
    system "#{bin}/ds-load version"
  end
end
