# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PatchUsers < Formula
  desc "Patch Users Support Tool"
  homepage "https://docs.aserto.com/"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://storage.googleapis.com/aserto-cli/patch-users/0.0.4/patch-users_darwin_arm64.zip", :using => CurlDownloadStrategy
      sha256 "11d73c117ef11a0da1be70ff35ff847e89cedc975c88de568a45b239ad119321"

      def install
        bin.install "patch-users"
      end
    end
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/aserto-cli/patch-users/0.0.4/patch-users_darwin_x86_64.zip", :using => CurlDownloadStrategy
      sha256 "9c76e35faf2af38e8fa666cf6fa45cd4c38ff8602a62b2acbb7da5895418d7e5"

      def install
        bin.install "patch-users"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://storage.googleapis.com/aserto-cli/patch-users/0.0.4/patch-users_linux_arm64.zip", :using => CurlDownloadStrategy
      sha256 "e273cb50b53b955cfcca7573e07c59ae9fd2c3812313c14dfceae64684fa8bc3"

      def install
        bin.install "patch-users"
      end
    end
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/aserto-cli/patch-users/0.0.4/patch-users_linux_x86_64.zip", :using => CurlDownloadStrategy
      sha256 "e5445784bf7c0e2f5b9c43fe3e69d85ff51c4da5c23a6806e1ae34f6da8aa497"

      def install
        bin.install "patch-users"
      end
    end
  end

  test do
    system "#{bin}/patch-users version"
  end
end
