# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sver < Formula
  desc "sver semantic version calculator"
  homepage "https://aserto.com/"
  version "1.3.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aserto-dev/sver/releases/download/v1.3.12/sver1.3.12_darwin_arm64.zip"
      sha256 "82046bf2c7c3004368ebb565798d38c071437d749311c81ebdc20db1c7bf1274"

      def install
        bin.install "sver"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aserto-dev/sver/releases/download/v1.3.12/sver1.3.12_darwin_x86_64.zip"
      sha256 "76ba2fa2faf625c462fda07e12560f13fc219203aac625f0701c4c735173700f"

      def install
        bin.install "sver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aserto-dev/sver/releases/download/v1.3.12/sver1.3.12_linux_x86_64.zip"
      sha256 "701f7e662c82f205d29bfd5842bb2569087bbd8f3ec48df9fa4902e440ad1eeb"

      def install
        bin.install "sver"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aserto-dev/sver/releases/download/v1.3.12/sver1.3.12_linux_arm64.zip"
      sha256 "401ecbf30ece34d87a49444d0c22daf74c246695bae2e563e284cf6eaf4f3b80"

      def install
        bin.install "sver"
      end
    end
  end

  test do
    system "#{bin}/sver version"
  end
end
