# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sver < Formula
  desc "sver semantic version calculator"
  homepage "https://aserto.com/"
  version "1.3.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aserto-dev/sver/releases/download/v1.3.10/sver1.3.10_darwin_arm64.zip"
      sha256 "a02468ba9cd2ccb687a32dc167ccb2dd924bca35c208d3c458c8a46d9d25d835"

      def install
        bin.install "sver"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aserto-dev/sver/releases/download/v1.3.10/sver1.3.10_darwin_x86_64.zip"
      sha256 "56485067ae4d6a73fc459b618f13ea4abce0d3e5f481363c66c90f980226566f"

      def install
        bin.install "sver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aserto-dev/sver/releases/download/v1.3.10/sver1.3.10_linux_arm64.zip"
      sha256 "82b734536ac9c7f8206fd0620fb84812322ff7a5bd7f20eb9a8eb03ff1586584"

      def install
        bin.install "sver"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aserto-dev/sver/releases/download/v1.3.10/sver1.3.10_linux_x86_64.zip"
      sha256 "36dd12c685c01e77bef5d108d7cf12e3da09f65e0b728a6ea591870778380889"

      def install
        bin.install "sver"
      end
    end
  end

  test do
    system "#{bin}/sver version"
  end
end
