# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Topaz < Formula
  desc "Topaz CLI"
  homepage "https://www.topaz.sh/docs/"
  version "0.32.28"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/aserto-dev/topaz/releases/download/v0.32.28/topaz_darwin_arm64.zip", using: CurlDownloadStrategy
      sha256 "18b10f881cfcaa39d213ad58fca52fd26416fbeac45e663aa6a0f4b1bdd5505b"

      def install
        bin.install "topaz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aserto-dev/topaz/releases/download/v0.32.28/topaz_darwin_x86_64.zip", using: CurlDownloadStrategy
      sha256 "4f26dd5b6938a696ef0dbb384eebf709524fd32f76842bfab73e39aa524fa6e6"

      def install
        bin.install "topaz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aserto-dev/topaz/releases/download/v0.32.28/topaz_linux_arm64.zip", using: CurlDownloadStrategy
      sha256 "f06670b4b7c8e7bf38b0999cceb6dc2d8d6efeef6c1e948e6539a57119c7cf0e"

      def install
        bin.install "topaz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aserto-dev/topaz/releases/download/v0.32.28/topaz_linux_x86_64.zip", using: CurlDownloadStrategy
      sha256 "e706bb2b9a6c0864040099c42629f1f8642fe3981205c3a0a4bbd02a19f0a448"

      def install
        bin.install "topaz"
      end
    end
  end

  test do
    system "#{bin}/topaz version"
  end
end
