# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Topaz < Formula
  desc "Topaz CLI"
  homepage "https://www.topaz.sh/docs/"
  version "0.20.24"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://storage.googleapis.com/topaz-cli/topaz/0.20.24/topaz_darwin_arm64.zip", using: CurlDownloadStrategy
      sha256 "f97d77c3a4c597faa0844d5e0fa5ee2c6f0754efda6ef310a592643ef90eb19d"

      def install
        bin.install "topaz"
      end
    end
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/topaz-cli/topaz/0.20.24/topaz_darwin_x86_64.zip", using: CurlDownloadStrategy
      sha256 "9dd865c4f919dbe7dcfb440b3dbf8e25946a89d8a909595ae186c5744fd77de8"

      def install
        bin.install "topaz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/topaz-cli/topaz/0.20.24/topaz_linux_x86_64.zip", using: CurlDownloadStrategy
      sha256 "6557c509b3947b67e0b253396b7b8b3f08361b8945ebcf928b93916e03f36d84"

      def install
        bin.install "topaz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://storage.googleapis.com/topaz-cli/topaz/0.20.24/topaz_linux_arm64.zip", using: CurlDownloadStrategy
      sha256 "ce852cda8d8e6f3f1790ad005646128acbc1a690733f64d42c47957ae183408f"

      def install
        bin.install "topaz"
      end
    end
  end

  test do
    system "#{bin}/topaz version"
  end
end
