# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Topaz < Formula
  desc "Topaz CLI"
  homepage "https://www.topaz.sh/docs/"
  version "0.20.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://storage.googleapis.com/topaz-cli/topaz/0.20.7/topaz_darwin_arm64.zip", :using => CurlDownloadStrategy
      sha256 "d63dc7964791d17c353817fa1245e8f412598fb889b9ed4ad01a5061d5c3abb5"

      def install
        bin.install "topaz"
      end
    end
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/topaz-cli/topaz/0.20.7/topaz_darwin_x86_64.zip", :using => CurlDownloadStrategy
      sha256 "b43a9533a5bbe7cb1a03286b885e11df703487a26681b0ffd64795abf8509d31"

      def install
        bin.install "topaz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/topaz-cli/topaz/0.20.7/topaz_linux_x86_64.zip", :using => CurlDownloadStrategy
      sha256 "339104d4f896c363918851ad7f9aae505b7979fa28696846cbc96604bb078879"

      def install
        bin.install "topaz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://storage.googleapis.com/topaz-cli/topaz/0.20.7/topaz_linux_arm64.zip", :using => CurlDownloadStrategy
      sha256 "0aa2781935b8b1f70aa78df0d03f834d51b18733638f4084763190cd66ae2837"

      def install
        bin.install "topaz"
      end
    end
  end

  test do
    system "#{bin}/topaz version"
  end
end
