# This file was generated by GoReleaser. DO NOT EDIT.
cask "topaz" do
  name "topaz"
  desc "Topaz CLI"
  homepage "https://www.topaz.sh/docs/"
  version "0.33.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "topaz"

  on_macos do
    on_intel do
      url "https://github.com/aserto-dev/topaz/releases/download/v#{version}/topaz_darwin_amd64.zip"
      sha256 "fe4ab2206dcb34b6fea436b9da3b7db54b1e15d135a3be39e59b5326a62d79a5"
    end
    on_arm do
      url "https://github.com/aserto-dev/topaz/releases/download/v#{version}/topaz_darwin_arm64.zip"
      sha256 "9013c31605b84639f58f211c29d8c96fcf128bab84f9d9434931e5e64e05ed6b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aserto-dev/topaz/releases/download/v#{version}/topaz_linux_amd64.zip"
      sha256 "c7e1b85f5dd80583bda93b4f97714b54951363a502811b433b7f26abbab7278e"
    end
    on_arm do
      url "https://github.com/aserto-dev/topaz/releases/download/v#{version}/topaz_linux_arm64.zip"
      sha256 "2087915fade2f618e9542fad18eaa749bae36b520d87659d71e315236d1d704b"
    end
  end

  # No zap stanza required
end
