# This file was generated by GoReleaser. DO NOT EDIT.
cask "topaz" do
  name "topaz"
  desc "Topaz CLI"
  homepage "https://www.topaz.sh/docs/"
  version "0.33.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "topaz"

  on_macos do
    on_intel do
      url "https://github.com/aserto-dev/topaz/releases/download/v#{version}/topaz_darwin_amd64.zip"
      sha256 "e8882493ddd294bdd0211fdee861bf1f18ddac9cfb0a5916a63a067c9a0c01b8"
    end
    on_arm do
      url "https://github.com/aserto-dev/topaz/releases/download/v#{version}/topaz_darwin_arm64.zip"
      sha256 "275ccf5073d04988754bb1e92ec4874aed9134e7e6a9ab0c8c78eb421841e7c2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aserto-dev/topaz/releases/download/v#{version}/topaz_linux_amd64.zip"
      sha256 "732ac884eb81c6fb626555261ca22232ff7d4a9ed29cf036b413208bb70da232"
    end
    on_arm do
      url "https://github.com/aserto-dev/topaz/releases/download/v#{version}/topaz_linux_arm64.zip"
      sha256 "5083f3feef684dcf2b16e0dd8412e9ee5f22fab7f6a9aed21aa07031384044a5"
    end
  end

  # No zap stanza required
end
